location            = "Central India"
resource_group_name = "rg-prod-linuxvm"
vm_name             = "prod-linux-vm"
vm_size             = "prod-linux-size"
admin_username      = "azureuser"
admin_password      = "Password@1234!"
